// MOVIES
export const SET_MOVIE = 'SET_MOVIE';
export const DELETE_A_MOVIE = 'DELETE_A_MOVIE';
export const LIKE_A_MOVIE = 'LIKE_A_MOVIE';
export const DISLIKE_A_MOVIE = 'DISLIKE_A_MOVIE';

// CATEGORIES
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
